"""Initial migration.

Revision ID: b13357a90c07
Revises: 
Create Date: 2022-03-24 16:34:21.946045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13357a90c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('post_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'blog_posts', 'categories', ['post_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'post_category_id')
    # ### end Alembic commands ###
